# Use the official MariaDB image as the base image
FROM mariadb:latest

# Set environment variables for MariaDB
ENV MYSQL_ROOT_PASSWORD=1234
ENV MYSQL_DATABASE=DDBBPROJ

# Expose the default MariaDB port
EXPOSE 3306